### ISSUE TITLE
Not AOT friendly

### ISSUE THREAD

**Issue by Ks89** [moff/angular2-ladda#8]
Hi!
I'm trying to build my application with Angular2 AOT, but angular2-ladda throws this error:

`Unexpected value 'LaddaModule in <MYPROJECT>/node_modules/angular2-ladda/module/module.d.ts' imported by the module 'AdminModule in <MYPROJECT>/src/admin/admin.module.ts'`

An interesting discussion [HERE](https://github.com/angular/angular/issues/11262)

Could you update this lib to support AOT?

Thank u.

**Comment by moff** [comment]
At the moment I'm traveling so I don't have time and opportunity to fix this issue. I'll take a look when I'll get back home. Sorry for that!

**Comment by theodorejb** [comment]
I created pull request #9 to add support for AOT.

**Comment by theodorejb** [comment]
This issue has been fixed as of v1.0.7 and can be closed.

**Comment by Ks89** [comment]
Ok. I'll try it tomorrow. But if you want feel free to close it XD

**Comment by Ks89** [comment]
With angular 2.4.4 I confirm that everything is ok.

Otherwise, with angular 4.0.0-beta.4 I get this error:
```
Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Can't resolve all parameters for LaddaConfig in <my project folder>/node_modules/angular2-ladda/module/ladda-config.d.ts: (?).
    at SyntaxError.BaseError [as constructor] (<my project folder>/node_modules/@angular/compiler/bundles/compiler.umd.js:1603:31)
    at new SyntaxError (<my project folder>/node_modules/@angular/compiler/bundles/compiler.umd.js:1801:20)
    at CompileMetadataResolver._getDependenciesMetadata (<my project folder>/node_modules/@angular/compiler/bundles/compiler.umd.js:18710:35)
    at CompileMetadataResolver._getTypeMetadata (<my project folder>/node_modules/@angular/compiler/bundles/compiler.umd.js:18585:30)
    at CompileMetadataResolver.getInjectableSummary (<my project folder>/node_modules/@angular/compiler/bundles/compiler.umd.js:18560:77)
    at <my project folder>/node_modules/@angular/compiler/bundles/compiler.umd.js:24853:387
    at Array.map (native)
    at AotCompiler._createSummary (<my project folder>/node_modules/@angular/compiler/bundles/compiler.umd.js:24853:335)
    at AotCompiler._compileSrcFile (<my project folder>/node_modules/@angular/compiler/bundles/compiler.umd.js:24809:38)
    at <my project folder>/node_modules/@angular/compiler/bundles/compiler.umd.js:24790:95
    at Array.map (native)
    at <my project folder>/node_modules/@angular/compiler/bundles/compiler.umd.js:24790:60
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

I know that angular 4 is only a beta.

**Comment by theodorejb** [comment]
Thanks for noticing the error with Angular 4, @Ks89. I've included a fix for it as part of pull request #10.

**Comment by theodorejb** [comment]
Should be all fixed now in v1.1.0!

**Comment by Ks89** [comment]
In a project with Angular 2.4.5 and angular2-ladda 1.0.6 everything is ok.
After the update to angular2-ladda 1.1.0 I can't compile, because I receive this error:

ERROR in [default] /Users/ks89/git/<MY PROJECT>t/node_modules/angular2-ladda/module/ladda-config.d.ts:9:19 
Cannot find name 'keyof'.

ERROR in [default] /Users/ks89/git/<MY PROJECT>/node_modules/angular2-ladda/module/ladda-config.d.ts:9:25 
';' expected.

**Comment by theodorejb** [comment]
@Ks89 `keyof` [is a new operator in TypeScript 2.1](https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/#keyof-and-lookup-types). The error should go away if you update your TypeScript dependency to v2.1+.

**Comment by Ks89** [comment]
@theodorejb yes. with typescript 2.1 it is working
thank u
